cache:
  paths:
    - .stack-root/
    - .stack-work/

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

.before_script_template: &common_before_script
  before_script:
    - apt-get update -y
    - apt-get install -y curl
    - mkdir -p ~/.local/bin
    - curl -L https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - export PATH=~/.local/bin:$PATH

.script_template: &common_script
  script:
    - stack --no-terminal --version
    - stack setup --no-terminal
    - stack update --no-terminal
    - stack build -j2 --fast --no-terminal
    - stack test --fast --no-terminal

ghc82x:
  image: haskell:8.2
  variables:
    STACK_YAML: stack-8.2.yaml
  <<: *common_before_script
  <<: *common_script

ghc84x:
  image: haskell:8.4
  variables:
    STACK_YAML: stack.yaml
  <<: *common_before_script
  <<: *common_script
