name: cdb
version: 0.1
synopsis: Incomplete Azure Cosmos DB client
description: See README
maintainer: Dmitry Malikov <malikov.d.y@gmail.com>
category: Web
license: BSD3

ghc-options:
  - -Wall
  - -fhide-source-paths
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fdefer-typed-holes

dependencies:
  - base >= 4.10.1
  - aeson
  - bytestring
  - case-insensitive
  - http-client
  - http-client-tls
  - http-types
  - safe-exceptions
  - text
  - time
  - unordered-containers

default-extensions:
  - DuplicateRecordFields
  - GADTs
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications
  - ViewPatterns

library:
  source-dirs: src
  dependencies:
    - case-insensitive
    - cryptohash-sha256
    - mime
    - random
    - uri-encode
    - vector
  exposed-modules:
    - Network.CosmosDB
    - Network.CosmosDB.Auth
    - Network.CosmosDB.Client.Collections
    - Network.CosmosDB.Client.Databases
    - Network.CosmosDB.Client.Documents
    - Network.CosmosDB.Core
    - Network.CosmosDB.Model.Collection
    - Network.CosmosDB.Model.Database
    - Network.CosmosDB.Model.IndexingPolicy
    - Network.CosmosDB.Request
    - Network.Http.Retry
  default-extensions:
    - DefaultSignatures
    - DeriveGeneric
    - GeneralizedNewtypeDeriving
    - StrictData

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - test/spec/
    dependencies:
      - aeson-qq
      - cdb
      - hspec
      - hspec-expectations
      - HUnit
      - lens
      - lens-aeson
    ghc-options:
      - -fno-warn-missing-fields
      - -threaded
      - -with-rtsopts=-N
    default-extensions:
      - DuplicateRecordFields
      - GADTs
      - LambdaCase
      - OverloadedStrings
      - RecordWildCards
